from __future__ import annotations

import json
import re
import textwrap
from collections import defaultdict
from typing import Any

from app.ir.schemas import EdgeKind, NodeIR, NodeType, ProjectIR


TYPE_MAP = {
    "str": "str",
    "string": "str",
    "int": "int",
    "integer": "int",
    "float": "float",
    "bool": "bool",
    "boolean": "bool",
    "dict": "dict[str, Any]",
    "object": "dict[str, Any]",
    "list": "list[Any]",
    "array": "list[Any]",
    "any": "Any",
}


def generate_project_files(project: ProjectIR) -> dict[str, str]:
    package = package_name(project)
    files = {
        "langgraph.json": _langgraph_json(package),
        "pyproject.toml": _pyproject_toml(package),
        ".env.example": _env_example(project),
        "README.md": _readme(project, package),
        f"src/{package}/__init__.py": "",
        f"src/{package}/config.py": _config_py(),
        f"src/{package}/state.py": _state_py(project),
        f"src/{package}/nodes.py": _nodes_py(project),
        f"src/{package}/routers.py": _routers_py(project),
        f"src/{package}/graph.py": _graph_py(project),
        "tests/test_graph_smoke.py": _smoke_test(package),
        "flow/project.graph.json": project.model_dump_json(by_alias=True, indent=2),
    }
    return files


def package_name(project: ProjectIR) -> str:
    source = project.project.id or project.project.name or "generated_agent"
    name = re.sub(r"[^a-zA-Z0-9_]+", "_", source).strip("_").lower()
    if not name:
        name = "generated_agent"
    if name[0].isdigit():
        name = f"agent_{name}"
    return name


def py_name(value: str) -> str:
    name = re.sub(r"[^a-zA-Z0-9_]+", "_", value).strip("_").lower()
    if not name:
        name = "node"
    if name[0].isdigit():
        name = f"node_{name}"
    return name


def _langgraph_json(package: str) -> str:
    return json.dumps(
        {
            "dependencies": ["."],
            "graphs": {"agent": f"./src/{package}/graph.py:graph"},
            "env": "./.env",
        },
        indent=2,
    )


def _pyproject_toml(package: str) -> str:
    return f"""[project]
name = "{package}"
version = "0.1.0"
description = "Generated LangGraph agent from GraphicLangGraph"
requires-python = ">=3.12"
dependencies = [
  "langgraph>=0.2.70",
  "langchain>=0.3.0",
  "langchain-core>=0.3.0",
  "httpx>=0.27.0"
]

[tool.pytest.ini_options]
pythonpath = ["src"]
"""


def _env_example(project: ProjectIR) -> str:
    keys = {"OPENAI_API_KEY": "replace_me"}
    for node in project.nodes:
        if node.type == NodeType.HTTP:
            secret = str(node.config.get("authSecret", "")).strip()
            if secret:
                keys[secret] = "replace_me"
    return "\n".join(f"{key}={value}" for key, value in sorted(keys.items())) + "\n"


def _readme(project: ProjectIR, package: str) -> str:
    return f"""# {project.project.name}

Generated by GraphicLangGraph.

## Install

```bash
python -m pip install -e .
```

## Run smoke test

```bash
python -m pytest
```

## LangGraph dev

```bash
langgraph dev
```

Graph entry: `{package}.graph:graph`
"""


def _config_py() -> str:
    return '''from __future__ import annotations

import os
import re
from typing import Any


TEMPLATE_RE = re.compile(r"{{\\s*state\\.([a-zA-Z_][a-zA-Z0-9_]*)\\s*}}")


def env(key: str, default: str = "") -> str:
    return os.getenv(key, default)


def render_template(template: str, state: dict[str, Any]) -> str:
    def replace(match: re.Match[str]) -> str:
        value = state.get(match.group(1), "")
        return "" if value is None else str(value)

    return TEMPLATE_RE.sub(replace, template)
'''


def _state_py(project: ProjectIR) -> str:
    lines = [
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "from typing_extensions import NotRequired",
        "from langgraph.graph import MessagesState",
        "",
        "",
        "class AgentState(MessagesState):",
    ]
    if not project.state.fields:
        lines.append("    pass")
    else:
        for field in project.state.fields:
            type_name = TYPE_MAP.get(field.type.lower(), "Any")
            lines.append(f"    {py_name(field.name)}: NotRequired[{type_name}]")
    return "\n".join(lines) + "\n"


def _nodes_py(project: ProjectIR) -> str:
    body = [
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "from pathlib import Path",
        "import httpx",
        "from langchain.chat_models import init_chat_model",
        "from langchain_core.messages import AIMessage",
        "",
        "from .config import env, render_template",
        "from .state import AgentState",
        "",
    ]
    for node in project.nodes:
        if node.type == NodeType.START:
            continue
        body.append(_node_function(node))
        body.append("")
    return "\n".join(body)


def _node_function(node: NodeIR) -> str:
    function_name = py_name(node.id)
    if node.type == NodeType.LLM:
        provider = json.dumps(str(node.config.get("provider", "openai")))
        model = json.dumps(str(node.config.get("model", "gpt-4.1-mini")))
        system_prompt = json.dumps(str(node.config.get("systemPrompt", "")))
        user_prompt = json.dumps(str(node.config.get("userPrompt", "{{ state.messages }}")))
        output_field = py_name(str(node.config.get("outputField", f"{function_name}_output")))
        return f'''def {function_name}(state: AgentState) -> dict[str, Any]:
    model = init_chat_model({model}, model_provider={provider})
    messages = [
        ("system", render_template({system_prompt}, state)),
        ("user", render_template({user_prompt}, state)),
    ]
    response = model.invoke(messages)
    return {{"{output_field}": getattr(response, "content", str(response))}}
'''
    if node.type == NodeType.AGENT:
        provider = json.dumps(str(node.config.get("provider", "openai")))
        model = json.dumps(str(node.config.get("model", "gpt-4.1-mini")))
        system_prompt = json.dumps(str(node.config.get("systemPrompt", "")))
        max_iterations = int(node.config.get("maxIterations", 4) or 4)
        output_field = py_name(str(node.config.get("outputField", f"{function_name}_result")))
        return f'''def {function_name}(state: AgentState) -> dict[str, Any]:
    model = init_chat_model({model}, model_provider={provider})
    messages = [
        ("system", render_template({system_prompt}, state)),
        ("user", str(state.get("messages", ""))),
    ]
    response = model.invoke(messages)
    return {{
        "{output_field}": getattr(response, "content", str(response)),
        "{py_name(function_name)}_max_iterations": {max_iterations},
    }}
'''
    if node.type == NodeType.TOOL:
        tool_name = json.dumps(str(node.config.get("toolName", node.label or function_name)))
        description = json.dumps(str(node.config.get("description", "")))
        params_json = json.dumps(str(node.config.get("paramsJson", "{}")))
        output_field = py_name(str(node.config.get("outputField", f"{function_name}_result")))
        requires_approval = bool(node.config.get("requiresApproval", False))
        return f'''def {function_name}(state: AgentState) -> dict[str, Any]:
    return {{
        "{output_field}": {{
            "tool": {tool_name},
            "description": {description},
            "params_schema": {params_json},
            "requires_approval": {requires_approval!r},
            "status": "configured",
        }}
    }}
'''
    if node.type == NodeType.RETRIEVER:
        path = json.dumps(str(node.config.get("path", "./knowledge")))
        query = json.dumps(str(node.config.get("query", "{{ state.messages }}")))
        top_k = int(node.config.get("topK", 4) or 4)
        output_field = py_name(str(node.config.get("outputField", f"{function_name}_context")))
        return f'''def {function_name}(state: AgentState) -> dict[str, Any]:
    query = render_template({query}, state).lower()
    root = Path({path})
    documents: list[str] = []
    if root.exists():
        for file_path in list(root.rglob("*.md")) + list(root.rglob("*.txt")):
            try:
                text = file_path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                continue
            if not query or any(part and part in text.lower() for part in query.split()):
                documents.append(text[:1600])
            if len(documents) >= {top_k}:
                break
    return {{"{output_field}": "\\n\\n---\\n\\n".join(documents)}}
'''
    if node.type == NodeType.HTTP:
        method = json.dumps(str(node.config.get("method", "GET")).upper())
        url = json.dumps(str(node.config.get("url", "")))
        body = json.dumps(str(node.config.get("body", "")))
        auth_secret = json.dumps(str(node.config.get("authSecret", "")))
        output_field = py_name(str(node.config.get("outputField", f"{function_name}_response")))
        return f'''def {function_name}(state: AgentState) -> dict[str, Any]:
    headers = {{}}
    token_key = {auth_secret}
    if token_key:
        headers["Authorization"] = f"Bearer {{env(token_key)}}"
    response = httpx.request(
        {method},
        render_template({url}, state),
        headers=headers,
        content=render_template({body}, state) if {body} else None,
        timeout=30,
    )
    response.raise_for_status()
    try:
        value = response.json()
    except ValueError:
        value = response.text
    return {{"{output_field}": value}}
'''
    if node.type == NodeType.CONDITION:
        return f'''def {function_name}(state: AgentState) -> dict[str, Any]:
    return {{}}
'''
    if node.type == NodeType.AI_ROUTER:
        input_text = json.dumps(str(node.config.get("inputText", "{{ state.messages }}")))
        route_field = py_name(str(node.config.get("routeField", "route_key")))
        reason_field = py_name(str(node.config.get("reasonField", "route_reason")))
        fallback = json.dumps(str(node.config.get("fallback", "other")))
        scenarios = json.dumps(_parse_scenarios(str(node.config.get("scenarios", ""))), ensure_ascii=False, indent=8)
        return f'''def {function_name}(state: AgentState) -> dict[str, Any]:
    text = render_template({input_text}, state).lower()
    scenarios = {scenarios}
    selected = {fallback}
    reason = "fallback"
    for scenario in scenarios:
        keywords = [item.strip().lower() for item in scenario.get("keywords", []) if item.strip()]
        if keywords and any(keyword in text for keyword in keywords):
            selected = scenario["id"]
            reason = f"matched keywords for {{scenario['label']}}"
            break
    return {{"{route_field}": selected, "{reason_field}": reason}}
'''
    if node.type == NodeType.HUMAN_APPROVAL:
        action_field = py_name(str(node.config.get("actionField", "approval_action")))
        output_field = py_name(str(node.config.get("outputField", "approval_result")))
        default_action = json.dumps(str(node.config.get("defaultAction", "approved")))
        prompt = json.dumps(str(node.config.get("prompt", "")))
        return f'''def {function_name}(state: AgentState) -> dict[str, Any]:
    action = str(state.get("{action_field}") or {default_action})
    return {{
        "{action_field}": action,
        "{output_field}": {{"action": action, "prompt": render_template({prompt}, state)}},
    }}
'''
    if node.type == NodeType.DIRECT_REPLY:
        template = json.dumps(str(node.config.get("template", "{{ state.final_answer }}")))
        output_field = py_name(str(node.config.get("outputField", "final_answer")))
        return f'''def {function_name}(state: AgentState) -> dict[str, Any]:
    content = render_template({template}, state)
    return {{
        "{output_field}": content,
        "messages": [AIMessage(content=content)],
    }}
'''
    if node.type == NodeType.CUSTOM_FUNCTION:
        code = str(node.config.get("code", "return {}"))
        output_field = py_name(str(node.config.get("outputField", f"{function_name}_output")))
        return f'''def {function_name}(state: AgentState) -> dict[str, Any]:
    result = _{function_name}_impl(state)
    if isinstance(result, dict):
        return result
    return {{"{output_field}": result}}


def _{function_name}_impl(state: AgentState):
{_indent(code)}
'''
    return f'''def {function_name}(state: AgentState) -> dict[str, Any]:
    return {{}}
'''


def _routers_py(project: ProjectIR) -> str:
    condition_nodes = [
        node
        for node in project.nodes
        if node.type in {NodeType.CONDITION, NodeType.AI_ROUTER, NodeType.HUMAN_APPROVAL}
    ]
    if not condition_nodes:
        return "from __future__ import annotations\n\n"

    body = [
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
        "from .state import AgentState",
        "",
    ]
    for node in condition_nodes:
        body.append(_route_function(node))
        body.append("")
    return "\n".join(body)


def _route_function(node: NodeIR) -> str:
    name = py_name(node.id)
    if node.type == NodeType.AI_ROUTER:
        route_field = py_name(str(node.config.get("routeField", "route_key")))
        fallback = str(node.config.get("fallback", "other"))
        return f'''def route_{name}(state: AgentState) -> str:
    return str(state.get("{route_field}") or {fallback!r})
'''
    if node.type == NodeType.HUMAN_APPROVAL:
        action_field = py_name(str(node.config.get("actionField", "approval_action")))
        fallback = str(node.config.get("fallback", "rejected"))
        return f'''def route_{name}(state: AgentState) -> str:
    return str(state.get("{action_field}") or {fallback!r})
'''
    field = py_name(str(node.config.get("field", "")))
    operator = str(node.config.get("operator", "equals"))
    value = str(node.config.get("value", ""))
    true_branch = str(node.config.get("trueBranch", "true"))
    false_branch = str(node.config.get("falseBranch", "false"))
    fallback = str(node.config.get("fallback", "fallback"))
    return f'''def route_{name}(state: AgentState) -> str:
    current = state.get("{field}")
    expected = {value!r}
    if _compare(current, expected, "{operator}"):
        return {true_branch!r}
    if {false_branch!r}:
        return {false_branch!r}
    return {fallback!r}


def _compare(current: Any, expected: str, operator: str) -> bool:
    current_text = "" if current is None else str(current)
    if operator == "not_equals":
        return current_text != expected
    if operator == "contains":
        return expected in current_text
    if operator == "not_contains":
        return expected not in current_text
    if operator == "is_empty":
        return not current_text
    if operator == "is_not_empty":
        return bool(current_text)
    return current_text == expected
'''


def _graph_py(project: ProjectIR) -> str:
    normal_edges = [edge for edge in project.edges if edge.kind != EdgeKind.CONDITIONAL]
    conditional_edges = [edge for edge in project.edges if edge.kind == EdgeKind.CONDITIONAL]
    condition_edge_map: dict[str, dict[str, str]] = defaultdict(dict)
    for edge in conditional_edges:
        condition_edge_map[edge.source][edge.sourceHandle or edge.label or "default"] = edge.target

    non_start_nodes = [node for node in project.nodes if node.type != NodeType.START]
    condition_ids = {
        node.id
        for node in project.nodes
        if node.type in {NodeType.CONDITION, NodeType.AI_ROUTER, NodeType.HUMAN_APPROVAL}
    }

    imports = ["from .nodes import " + ", ".join(py_name(node.id) for node in non_start_nodes)]
    condition_nodes = [node for node in non_start_nodes if node.id in condition_ids]
    if condition_nodes:
        imports.append("from .routers import " + ", ".join(f"route_{py_name(node.id)}" for node in condition_nodes))

    lines = [
        "from __future__ import annotations",
        "",
        "from langgraph.graph import START, END, StateGraph",
        "",
        "from .state import AgentState",
        *imports,
        "",
        "",
        "builder = StateGraph(AgentState)",
        "",
    ]

    for node in non_start_nodes:
        lines.append(f'builder.add_node("{node.id}", {py_name(node.id)})')
    lines.append("")

    start_ids = {node.id for node in project.nodes if node.type == NodeType.START}
    direct_reply_ids = {node.id for node in project.nodes if node.type == NodeType.DIRECT_REPLY}
    for edge in normal_edges:
        if edge.source in start_ids:
            lines.append(f'builder.add_edge(START, "{edge.target}")')
        elif edge.source not in direct_reply_ids:
            lines.append(f'builder.add_edge("{edge.source}", "{edge.target}")')

    for source, mapping in condition_edge_map.items():
        lines.append(
            textwrap.dedent(
                f'''
                builder.add_conditional_edges(
                    "{source}",
                    route_{py_name(source)},
                    {json.dumps(mapping, indent=4)},
                )
                '''
            ).strip()
        )

    for reply_id in direct_reply_ids:
        lines.append(f'builder.add_edge("{reply_id}", END)')

    lines.extend(["", "graph = builder.compile()", ""])
    return "\n".join(lines)


def _smoke_test(package: str) -> str:
    return f'''def test_graph_compiles():
    from {package}.graph import graph

    assert graph is not None
'''


def _parse_scenarios(value: str) -> list[dict[str, Any]]:
    scenarios: list[dict[str, Any]] = []
    for line in value.splitlines():
        line = line.strip()
        if not line:
            continue
        scenario_id, label, keywords = (line.split(":", 2) + ["", ""])[:3]
        scenario_id = scenario_id.strip()
        if not scenario_id:
            continue
        scenarios.append(
            {
                "id": scenario_id,
                "label": label.strip() or scenario_id,
                "keywords": [item.strip() for item in keywords.split(",") if item.strip()],
            }
        )
    return scenarios


def _indent(code: str) -> str:
    lines = code.splitlines() or ["return {}"]
    return "\n".join(f"    {line}" if line.strip() else "" for line in lines)
